# Generated by Django 4.2 on 2025-02-01 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format '01XXXXXXXXX' and be exactly 11 digits long.", regex='^01\\d{9}$')])),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('thana', models.CharField(blank=True, max_length=255, null=True)),
                ('upazila', models.CharField(blank=True, max_length=255, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('has_computer_laptop', models.BooleanField(default=False)),
                ('can_manage_laptop', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('sort', models.CharField(blank=True, max_length=255, null=True)),
                ('picture', models.FileField(blank=True, null=True, upload_to='teachers/')),
                ('other_info', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
